export const LEADERBOARD_DATA_REQUEST_INITIATE = 'LEADERBOARD_DATA_REQUEST_INITIATE';
export const LEADERBOARD_DATA_REQUEST_SUCCESS = 'LEADERBOARD_DATA_REQUESTED';
export const LEADERBOARD_DATA_REQUEST_FAILURE = 'LEADERBOARD_DATA_REQUESTED';
export const CHANGE_SELECTED_HUNT = 'CHANGE_SELECTED_HUNT';

